version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack CoreUtils\CoreUtils.csproj -Version $env:appveyor_build_version -IncludeReferencedProjects
artifacts:
- path: '*.nupkg'