version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  nuget sources add -name CSharpRuleSet -source https://ci.appveyor.com/nuget/csharpruleset-rxwtqx7d05sl
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
#test:
#  assemblies:
#    only:
#    - '**\bin\release\**\*Tests.dll'
test_script:
- ps: >-
    dotnet test CoreUtils.Tests\System1Group.Lib.CoreUtils.Tests.csproj
after_build:
- ps: dotnet pack CoreUtils\System1Group.Lib.CoreUtils.csproj
artifacts:
- path: '*.nupkg'