version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
 nuget sources add -name CSharpRuleSet -source https://ci.appveyor.com/nuget/csharpruleset-rxwtqx7d05sl
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack CoreUtils\CoreUtils.csproj -Version $env:appveyor_build_version -IncludeReferencedProjects
artifacts:
- path: '*.nupkg'